spring.datasource.url=jdbc:postgresql://localhost:5432/fitnessdb?currentSchema=public
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username=fitness
spring.datasource.password=${DB_PASSWORD}

openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.model=openrouter/free

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

