spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitnessdb?currentSchema=public}
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fitness}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

gemini.api.key=${GEMINI_API_KEY:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true